defaults: &defaults
  REQUEST_LIMIT_MAILER: 'develop@digitalnz.org'
  HTTP_HOST: 'http://test.host'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults