development:
  sessions:
    default:
      database: supplejack_api_development
      hosts:
        <%= ENV['MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        consistency: :strong

    strong:
      database: supplejack_api_development
      hosts:
        <%= ENV['MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        consistency: :strong

test:
  sessions:
    default:
      database: supplejack_api_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

    strong:
      database: supplejack_api_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong