# The majority of the Supplejack code is Crown copyright (C) 2014, New Zealand Government, 
# and is licensed under the GNU General Public License, version 3.
# Some components are third party components licensed under the GPL or MIT licenses 
# or otherwise publicly available. See https://github.com/DigitalNZ/supplejack_api for details. 
# 
# Supplejack was created by DigitalNZ at the National Library of NZ and 
# the Department of Internal Affairs. http://digitalnz.org/supplejack

development:
  sessions:
    default:
      database: supplejack_api_development
      hosts:
        <%= ENV['MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        consistency: :strong

    strong:
      database: supplejack_api_development
      hosts:
        <%= ENV['MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        consistency: :strong

test:
  sessions:
    default:
      database: supplejack_api_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

    strong:
      database: supplejack_api_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong