# The majority of the Supplejack API code is Crown copyright (C) 2014, New Zealand Government, 
# and is licensed under the GNU General Public License, version 3.
# One component is a third party component. See https://github.com/DigitalNZ/supplejack_api for details. 
# 
# Supplejack was created by DigitalNZ at the National Library of NZ and 
# the Department of Internal Affairs. http://digitalnz.org/supplejack

defaults: &defaults
  solr: &solr
    hostname: localhost
    port: 8983
    path: /solr
    log_level: DEBUG

development:
  <<: *defaults
    
test:
  <<: *defaults

# Uncomment this to configure staging environment
# staging:
#   <<: *defaults
#   solr:
#     port: 8080
#     path: '/solr4'
#     log_level: WARNING 
#     pid_dir: '/var/run/tomcat'
#     auto_commit_after_request: false

# Uncomment this to configure production environment
# production:
#   <<: *defaults
#   solr:
#     port: 8180
#     path: /solr4
#     auto_commit_after_request: false
