defaults: &defaults
  solr: &solr
    hostname: localhost
    port: 8983
    path: /solr
    log_level: DEBUG

development:
  <<: *defaults
    
test:
  <<: *defaults

# Uncomment this to configure staging environment
# staging:
#   <<: *defaults
#   solr:
#     port: 8080
#     path: '/solr4'
#     log_level: WARNING 
#     pid_dir: '/var/run/tomcat'
#     auto_commit_after_request: false

# Uncomment this to configure production environment
# production:
#   <<: *defaults
#   solr:
#     port: 8180
#     path: /solr4
#     auto_commit_after_request: false
