development:
  solr:
    hostname: localhost
    port: 8983
    path: /solr
    log_level: DEBUG

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: DEBUG

staging:
  solr:
    hostname: localhost
    port: 8080
    path: '/solr4'
    log_level: WARNING 
    pid_dir: '/var/run/tomcat'
    auto_commit_after_request: false

production:
  solr:
    hostname: localhost
    port: 8180
    path: /solr4
    auto_commit_after_request: false
